<?php
namespace App\Controller;

class ArticlesController extends AppController
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->loadComponent('RequestHandler');
    }

    public function index()
    {

        $this->loadComponent('Paginator');
        $articles = $this->Paginator->paginate($this->Articles->find());


        $this->set([
            'articles' => $articles,
            '_serialize' => ['articles']
        ]);
    }
}

?>
