<?php
namespace App\Controller;

class RestController extends AppController
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->loadComponent('RequestHandler');
    }

    public function index()
    {

        $this->set([
            'name' => 'Swann',
            '_serialize' => ['name']
        ]);
    }
}

?>
